# -*- coding: utf-8 -*-
"""Fake News.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17areAevux-qGcEQhXDGmGqbzWhkmCvoO
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

true = pd.read_csv("True.csv", encoding="latin-1")
fake = pd.read_csv("Fake.csv", encoding="latin-1", on_bad_lines="skip")

true["label"] = 0
fake["label"] = 1

df = pd.concat([true, fake], axis=0)
df = df.sample(frac=1).reset_index(drop=True)

X = df["text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

vectorizer = TfidfVectorizer(stop_words="english", max_df=0.7)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

model = LogisticRegression(max_iter=2000)
model.fit(X_train_tfidf, y_train)

y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))